//! HTTP query server for the siglake Iceberg warehouse.
//!
//! BYOC deployments need an authenticated, well-bounded HTTP API for
//! customer queries — `kubectl exec` is not an acceptable workflow.
//!
//! Endpoints (4.6):
//!
//! - `POST /api/v1/sql`  — DataFusion SQL over `events` and managed indexes.
//! - `GET /healthz`  — liveness probe.
//! - `GET /readyz`   — readiness probe; round-trips the catalog.
//!
//! Authentication: see [`AuthConfig`] for the three supported modes
//! (open / bearer / OIDC).

pub mod admission;
pub mod audit;
pub mod auth;
pub mod coordinator;
pub mod cost;
mod debug_routes;
mod delete_tasks_routes;
pub mod discovery;
pub mod error;
pub mod format;
mod health;
pub mod hot_cache;
mod indexes_routes;
pub mod jaeger_limits;
mod jaeger_routes;
pub mod jobs;
mod jobs_routes;
pub mod limits;
pub mod midflight;
pub mod oidc;
pub mod openapi_dto;
mod sql;
pub mod tenants;
pub mod udfs;
pub mod wal_buffer;

use std::net::SocketAddr;
use std::sync::Arc;

use anyhow::{Context, Result};
use axum::extract::MatchedPath;
use axum::middleware::{self, Next};
use axum::response::Response;
// NOTE: no `axum::routing::{get, post, ..}` import — method routers are
// generated by `utoipa_axum::routes!` from each handler's `#[utoipa::path]`
// annotation.
use axum::Router;
use datafusion::prelude::SessionContext;
use opentelemetry::global;
use opentelemetry_http::HeaderExtractor;
use tracing::Instrument;
use utoipa::OpenApi as _;
use utoipa_axum::router::OpenApiRouter;
use utoipa_axum::routes;

use siglake_storage::iceberg::IcebergContext;

pub use audit::{
    AuditAppender, AuditLimits, AuditRow, AuditService, AuditStatus, AuditUsage, AuditWriter,
    DEFAULT_AUDIT_APPEND_DEADLINE, DEFAULT_AUDIT_LIMITS,
};
pub use auth::{AuthConfig, CallerIdentity};
pub use error::ApiError;
pub use jobs::{CompletionOutcome, JobId, JobStatus, JobStore};
pub use limits::{Priority, RequestLimits, ResolvedLimits, TierLimits};
pub use oidc::OidcVerifier;
// Test seam only (`#[doc(hidden)]` at its definition in `sql.rs`): the result
// store is a process-wide static, so a measurement's phases cannot otherwise
// start from a stated state.
pub use sql::reset_result_cache_for_test;
pub use tenants::TenantRegistry;

/// Server-side per-tier ceilings. Per-request overrides clamp against
/// these — a request can ask for less but never more.
///
/// `max_rows` lives outside the per-tier structure for backward compat
/// with chunk-1 callers; it is the *interactive* tier's row cap (and
/// applies when no `Priority` is set). The full per-tier ceilings
/// live in `interactive` / `batch`.
#[derive(Debug, Clone)]
pub struct ServerLimits {
    pub max_rows: usize,
    pub interactive: TierLimits,
    pub batch: TierLimits,
    /// Per-process query admission budget, shared by interactive requests and
    /// asynchronous batch jobs. Tunable via
    /// `SIGLAKE_QUERY_ADMISSION_BUDGET_BYTES` in Helm/env. Batch jobs stay on
    /// their detached CPU runtime but reserve a fixed quarter of this budget;
    /// interactive reservations use a cost-derived share capped at a quarter
    /// by default. Overflow submissions get 429 rather than oversubscribing the
    /// process-wide memory pool.
    pub admission_budget_bytes: u64,
    /// Multiplier applied to `estimated_bytes_scanned` when reserving
    /// interactive admission bytes. Tunable via
    /// `SIGLAKE_QUERY_ADMISSION_DECOMPRESSION_FACTOR`; models decoded working
    /// set rather than compressed Parquet bytes.
    pub admission_decompression_factor: u64,
    /// How long an interactive query or batch submission will wait for
    /// admission before returning 429. Tunable via
    /// `SIGLAKE_QUERY_ADMISSION_WAIT_MS`.
    pub admission_wait_timeout: std::time::Duration,
}

impl Default for ServerLimits {
    fn default() -> Self {
        // The interactive mid-flight breaker ceilings are operator-tunable: the
        // 100M-row / 100GB defaults suit ~50G datasets, but a legitimately large
        // scan at scale (e.g. a 25% time-window aggregate over 400M rows ≈ 98M
        // rows) trips the fixed row cap → 413 instead of degrading to slow. Sizing
        // for the dataset (rows ≈ a few × the largest expected windowed scan)
        // lets those queries complete; the wall-clock timeout + admission budget
        // still bound runaway work. The batch tier keeps its much higher ceilings.
        let mut interactive = TierLimits::interactive_defaults();
        if let Some(v) = std::env::var("SIGLAKE_QUERY_CEILING_ROWS_SCANNED")
            .ok()
            .and_then(|v| v.parse::<usize>().ok())
            .filter(|n| *n > 0)
        {
            interactive.ceiling_rows_scanned = v;
        }
        if let Some(gb) = std::env::var("SIGLAKE_QUERY_CEILING_BYTES_SCANNED_GB")
            .ok()
            .and_then(|v| v.parse::<u64>().ok())
            .filter(|n| *n > 0)
        {
            interactive.ceiling_bytes_scanned = gb.saturating_mul(1024 * 1024 * 1024);
        }
        Self {
            max_rows: 1_000_000,
            interactive,
            batch: TierLimits::batch_defaults(),
            admission_budget_bytes: std::env::var("SIGLAKE_QUERY_ADMISSION_BUDGET_BYTES")
                .ok()
                .and_then(|v| v.parse().ok())
                .unwrap_or_else(default_admission_budget_bytes),
            admission_decompression_factor: std::env::var(
                "SIGLAKE_QUERY_ADMISSION_DECOMPRESSION_FACTOR",
            )
            .ok()
            .and_then(|v| v.parse().ok())
            .filter(|n: &u64| *n > 0)
            .unwrap_or(4),
            admission_wait_timeout: std::env::var("SIGLAKE_QUERY_ADMISSION_WAIT_MS")
                .ok()
                .and_then(|v| v.parse().ok())
                .map(std::time::Duration::from_millis)
                .unwrap_or_else(|| std::time::Duration::from_secs(2)),
        }
    }
}

impl ServerLimits {
    /// Effective tier limits for `priority`, with the global
    /// [`ServerLimits::max_rows`] cap folded in (it can only tighten,
    /// never loosen, the tier ceiling).
    pub fn tier(&self, priority: Priority) -> TierLimits {
        let mut t = match priority {
            Priority::Interactive => self.interactive.clone(),
            Priority::Batch => self.batch.clone(),
        };
        t.ceiling_rows_returned = t.ceiling_rows_returned.min(self.max_rows);
        t
    }
}

#[derive(Debug, Clone, Copy, Default)]
pub struct QueryScanConfig {
    pub target_partitions: Option<usize>,
    pub reader_budget: Option<usize>,
    pub file_concurrency_limit: Option<usize>,
    pub batch_size: Option<usize>,
    pub range_coalesce_bytes: Option<u64>,
    pub range_fetch_concurrency: Option<usize>,
    pub range_adaptive_min_bytes: Option<u64>,
    pub range_adaptive_min_files: Option<usize>,
    pub adaptive_partition_min_bytes: Option<u64>,
    pub adaptive_partition_min_files: Option<usize>,
    pub file_cache_max_bytes: Option<u64>,
    pub file_cache_max_entries: Option<usize>,
    pub ordered_merge_max_fan_in: Option<usize>,
    pub ordered_sort_cluster_max_rows: Option<u64>,
    pub reversed_chunk_rows: Option<usize>,
    pub bypass_reader_caches: bool,
    pub ordered_drain_buffer_bytes: Option<u64>,
}

impl QueryScanConfig {
    pub fn session_context(self) -> SessionContext {
        self.session_context_with_order(None)
    }

    pub fn session_context_with_order(
        self,
        preferred_scan_order: Option<siglake_storage::PreferredScanOrder>,
    ) -> SessionContext {
        self.with_ordered_tuning(siglake_storage::session_context_with_order(
            self.target_partitions,
            None,
            preferred_scan_order,
        ))
    }

    /// Per-request context carrying a distributed-query [`ScanShard`] (#7) when
    /// `Some` — the worker then scans only that shard's files.
    pub fn session_context_sharded(
        self,
        shard: Option<siglake_storage::ScanShard>,
    ) -> SessionContext {
        self.session_context_sharded_with_order(shard, None)
    }

    pub fn session_context_sharded_with_order(
        self,
        shard: Option<siglake_storage::ScanShard>,
        preferred_scan_order: Option<siglake_storage::PreferredScanOrder>,
    ) -> SessionContext {
        self.with_ordered_tuning(siglake_storage::session_context_with_order(
            self.target_partitions,
            shard,
            preferred_scan_order,
        ))
    }

    fn with_ordered_tuning(self, ctx: SessionContext) -> SessionContext {
        let mut state = ctx.state();
        state
            .config_mut()
            .set_extension(Arc::new(siglake_storage::OrderedScanTuning {
                merge_max_fan_in: self.ordered_merge_max_fan_in,
                sort_cluster_max_rows: self.ordered_sort_cluster_max_rows,
                reversed_chunk_rows: self.reversed_chunk_rows,
                bypass_reader_caches: self.bypass_reader_caches,
                ordered_drain_buffer_bytes: self.ordered_drain_buffer_bytes,
            }));
        SessionContext::new_with_state(state)
    }
}

/// State shared across handlers. Cheap to clone (a few `Arc`s).
///
/// `ice` is intentionally long-lived: the catalog connection pool and
/// any cached namespace handles inside [`IcebergContext`] stay warm
/// across requests. The DataFusion `SessionContext` is *not* long-lived
/// — it's recreated per-request so each query sees a fresh table
/// snapshot (Iceberg's `IcebergStaticTableProvider` caches the snapshot
/// at registration time). Recreating the SessionContext also lets
/// concurrent queries run in parallel rather than serializing on a
/// shared mutex.
#[derive(Clone)]
pub struct AppState {
    pub ice: Arc<IcebergContext>,
    pub auth: Arc<AuthConfig>,
    pub limits: Arc<ServerLimits>,
    pub admission: Arc<crate::admission::AdmissionController>,
    pub jobs: Arc<JobStore>,
    /// Audit handle. `None` disables audit emission.
    pub audit: Option<AuditWriter>,
    /// Per-request tenant routing. `None` ⇒ every request routes
    /// through `ice` (the v0 single-tenant behavior).
    pub tenants: Option<TenantRegistry>,
    /// Exact set of named tenants this query process admits. `None` keeps the
    /// compatibility default: every verified, usable tenant claim is allowed.
    /// This is deliberately independent of ingest admission so a tenant whose
    /// writes have stopped can remain readable through its retention window.
    pub allowed_tenants: Option<Arc<std::collections::HashSet<String>>>,
    /// Query scan tuning for per-request SessionContext creation.
    pub query_scan: QueryScanConfig,
    /// Where distributed-query membership comes from (#7 part 2b, #967): a
    /// static `--query-peers` list or the SRV discovery directory. `None` ⇒
    /// this node is not a coordinator; `/api/v1/sql/distributed` returns 400.
    /// The node always serves `/api/v1/sql/shard` as a worker.
    ///
    /// Every request captures ONE immutable
    /// [`crate::discovery::PeerSnapshot`] from this and uses it for the shard
    /// count, the shard→peer mapping, and failover — membership must not move
    /// under a query. Under discovery the capture can be `None` before the
    /// first usable DNS answer, which runs the query locally.
    pub peers: Option<crate::discovery::PeerSource>,
    /// Bearer token the coordinator presents to peer workers (when they
    /// enforce auth). `None` ⇒ peers must accept unauthenticated requests.
    pub coordinator_token: Option<String>,
    /// WS-6 real-time queryability: when `Some`, `events` queries union the
    /// Iceberg snapshot with the un-committed WAL segments under this root
    /// (per-tenant subdir resolved per request). `None` ⇒ disabled (the
    /// historical commit-cycle visibility). Requires the query pod to see the
    /// ingester's WAL — a shared RWX volume (EFS) in the distributed
    /// deployment.
    pub wal_buffer_dir: Option<Arc<std::path::Path>>,
    /// #78: per-table cache of decoded buffer batches, keyed on the exact
    /// segment-basename set (+ schema + carrier). Keeps fast-path answers ~ms
    /// while the buffer is non-empty — the delta decode runs once per buffer
    /// state, not once per request. Always present; only touched when
    /// `wal_buffer_dir` is set.
    pub buffer_delta_cache: Arc<crate::wal_buffer::BufferDeltaCache>,
    /// WS-6 query-tier hot caches (last-value + distinct). When `Some`, a
    /// background task tails the WAL root and each query registers the
    /// `last_values()`/`distinct_values(<dim>)` UDTFs bound to its tenant's
    /// cache. `None` ⇒ disabled.
    pub hot_caches: Option<Arc<crate::hot_cache::HotCacheRegistry>>,
    /// Unit-test rendezvous at the exact distributed merge boundary: after the
    /// coordinator has built its WAL partial, before it dispatches shards.
    #[cfg(test)]
    pub(crate) distributed_dispatch_hook: Option<Arc<DistributedDispatchHook>>,
}

#[cfg(test)]
#[derive(Default)]
pub(crate) struct DistributedDispatchHook {
    pub(crate) captured: tokio::sync::Notify,
    pub(crate) resume: tokio::sync::Notify,
}

impl AppState {
    pub fn new(ice: Arc<IcebergContext>, auth: AuthConfig) -> Self {
        let limits = ServerLimits::default();
        Self {
            ice,
            auth: Arc::new(auth),
            admission: Arc::new(crate::admission::AdmissionController::new(
                limits.admission_budget_bytes,
                limits.admission_decompression_factor,
                limits.admission_wait_timeout,
            )),
            limits: Arc::new(limits),
            jobs: Arc::new(JobStore::default()),
            audit: None,
            tenants: None,
            allowed_tenants: None,
            query_scan: QueryScanConfig::default(),
            peers: None,
            coordinator_token: None,
            wal_buffer_dir: None,
            buffer_delta_cache: Arc::new(crate::wal_buffer::BufferDeltaCache::default()),
            hot_caches: None,
            #[cfg(test)]
            distributed_dispatch_hook: None,
        }
    }

    /// Enable WS-6 real-time queryability: `events` queries union the Iceberg
    /// snapshot with the un-committed WAL segments under `dir`. Empty/unset ⇒
    /// disabled.
    pub fn with_wal_buffer_dir(mut self, dir: Option<std::path::PathBuf>) -> Self {
        self.wal_buffer_dir = dir.map(Arc::from);
        self
    }

    /// Enable the WS-6 query-tier hot caches over the WAL root `dir`. A
    /// background task ([`spawn_hot_cache_refresher`]) folds fresh segments into
    /// the per-tenant caches every `interval`; queries get the `last_values()` /
    /// `distinct_values(<dim>)` UDTFs. Empty/unset ⇒ disabled.
    pub fn with_hot_caches(
        mut self,
        dir: Option<std::path::PathBuf>,
        cfg: crate::hot_cache::HotCacheConfig,
    ) -> Self {
        self.hot_caches = dir.map(|d| Arc::new(crate::hot_cache::HotCacheRegistry::new(d, cfg)));
        self
    }

    /// Configure a STATIC distributed-query peer list (one base URL per shard)
    /// and the bearer token used to call them. Enables
    /// `/api/v1/sql/distributed`. Static mode keeps its legacy contract that
    /// the coordinator is peer zero; see [`Self::with_peer_source`] for the
    /// discovery path.
    pub fn with_coordinator(mut self, peers: Vec<String>, token: Option<String>) -> Self {
        self.peers = crate::discovery::PeerSource::from_static(peers);
        self.coordinator_token = token;
        self
    }

    /// Configure the peer source directly — used by the binary to install the
    /// SRV discovery directory, whose membership is published asynchronously.
    pub fn with_peer_source(
        mut self,
        peers: Option<crate::discovery::PeerSource>,
        token: Option<String>,
    ) -> Self {
        self.peers = peers;
        self.coordinator_token = token;
        self
    }

    pub fn with_limits(mut self, limits: ServerLimits) -> Self {
        self.admission = Arc::new(crate::admission::AdmissionController::new(
            limits.admission_budget_bytes,
            limits.admission_decompression_factor,
            limits.admission_wait_timeout,
        ));
        self.limits = Arc::new(limits);
        self
    }

    pub fn with_jobs(mut self, jobs: JobStore) -> Self {
        self.jobs = Arc::new(jobs);
        self
    }

    pub fn with_audit(mut self, audit: AuditWriter) -> Self {
        self.audit = Some(audit);
        self
    }

    pub fn with_tenants(mut self, tenants: TenantRegistry) -> Self {
        self.tenants = Some(tenants);
        self
    }

    pub fn with_allowed_tenants<I, S>(mut self, tenants: I) -> Self
    where
        I: IntoIterator<Item = S>,
        S: Into<String>,
    {
        let tenants: std::collections::HashSet<_> = tenants.into_iter().map(Into::into).collect();
        self.allowed_tenants = (!tenants.is_empty()).then(|| Arc::new(tenants));
        self
    }

    /// Refuse a named tenant outside this process's query allow-list.
    ///
    /// Callers must invoke this only after the tenant identifier has passed
    /// [`crate::tenants::validate`]. It intentionally admits `None`: the list
    /// bounds verified named claims and does not create a routing mode for
    /// open or static-token authentication.
    pub fn authorize_tenant(&self, identity: &CallerIdentity) -> Result<(), ApiError> {
        let (Some(allowed), Some(tenant)) = (&self.allowed_tenants, identity.tenant.as_deref())
        else {
            return Ok(());
        };
        if allowed.contains(tenant) {
            return Ok(());
        }
        metrics::counter!("siglake_query_tenant_denied_total", "reason" => "not_allowed")
            .increment(1);
        Err(ApiError::forbidden(
            "tenant is not in this query server's allowed tenant set",
        ))
    }

    pub fn with_query_scan(mut self, query_scan: QueryScanConfig) -> Self {
        self.query_scan = query_scan;
        self
    }

    /// Resolve the [`IcebergContext`] to use for this request. When
    /// tenant routing is enabled and the caller's identity carries a
    /// tenant claim, returns the per-tenant context; otherwise
    /// returns the default. Errors when a tenant namespace can't be
    /// opened (catalog unreachable, etc.) — those bubble up as a
    /// 500.
    pub async fn resolve_ice(
        &self,
        identity: &CallerIdentity,
    ) -> anyhow::Result<Arc<IcebergContext>> {
        match (&self.tenants, identity.tenant.as_deref()) {
            (Some(reg), Some(t)) => reg.resolve(t).await,
            _ => Ok(self.ice.clone()),
        }
    }

    /// The owner key for a batch job: the same thing that decides which
    /// `IcebergContext` this caller reads.
    ///
    /// Deliberately derived from the SAME match as [`Self::resolve_ice`] rather
    /// than from `identity.tenant` directly, so the rule is one sentence with no
    /// second interpretation: if two callers would read the same data, they can
    /// see each other's jobs; if they would not, they cannot. In particular a
    /// deployment with no tenant registry routes everyone to the default
    /// context, so job ownership must not start discriminating there either.
    ///
    /// The value is used as given. It used to be re-sanitized here, which was
    /// the same lossy mapping the registry applied and had the same
    /// consequence — two claims that differ only outside `[A-Za-z0-9_-]` owned
    /// each other's jobs. Nothing sanitizes now: `identity.tenant` is `Some`
    /// only after [`crate::tenants::validate`] accepted it, so the owner key
    /// and the namespace suffix are the same string by construction.
    pub fn job_owner(&self, identity: &CallerIdentity) -> Option<String> {
        match (&self.tenants, identity.tenant.as_deref()) {
            (Some(_), Some(t)) => Some(t.to_string()),
            _ => None,
        }
    }
}

/// OpenAPI document root for the query server.
///
/// Serialized to `docs/api/openapi-query.yaml` by the `siglake-openapi` bin.
/// There is deliberately no runtime endpoint that serves it — see
/// `docs/api/README.md`.
#[derive(utoipa::OpenApi)]
#[openapi(
    info(
        title = "siglake query",
        description = "DataFusion SQL over the Iceberg tables, index and \
                       index-template management, batch jobs, GDPR delete tasks, and a \
                       Jaeger-compatible trace read API.\n\n\
                       Ingest lives on a separate server (`openapi-ingest.yaml`) — this \
                       one only reads, apart from index management and delete tasks.",
        license(name = "Apache-2.0"),
    ),
    servers((url = "http://localhost:8089", description = "Default `--bind` address")),
    tags(
        (name = "health", description = "Liveness and readiness probes. Unauthenticated."),
        (name = "sql", description = "Query execution and cost estimation."),
        (name = "indexes", description = "Index configuration CRUD."),
        (name = "index-templates",
         description = "Mappings applied to indexes created later, matched by glob."),
        (name = "jobs", description = "Batch-query job lifecycle."),
        (name = "delete-tasks", description = "Asynchronous targeted row deletion (GDPR)."),
        (name = "debug", description = "Authenticated process diagnostics."),
        (name = "jaeger",
         description = "Jaeger-compatible trace read API, so the Jaeger UI can point here \
                        unchanged."),
    ),
    // Global default. Unauthenticated operations opt out with `security(())`.
    security(("query_token" = [])),
    modifiers(&SecurityAddon),
)]
struct ApiDoc;

struct SecurityAddon;

impl utoipa::Modify for SecurityAddon {
    fn modify(&self, openapi: &mut utoipa::openapi::OpenApi) {
        use utoipa::openapi::security::{HttpAuthScheme, HttpBuilder, SecurityScheme};
        // utoipa 5's `components(...)` attribute accepts only `schemas` and
        // `responses`, so a security scheme has to be added through a
        // `Modify` impl. `get_or_insert_default` because `components` may be
        // None before any schema is collected.
        openapi
            .components
            .get_or_insert_default()
            .add_security_scheme(
                "query_token",
                SecurityScheme::Http(
                    HttpBuilder::new()
                        .scheme(HttpAuthScheme::Bearer)
                        .description(Some(
                            "`Authorization: Bearer <token>`. With OIDC configured the \
                             token is a JWT and its claims select the tenant; otherwise it \
                             is matched against the cluster's static token list. A server \
                             started with neither accepts unauthenticated requests.",
                        ))
                        .build(),
                ),
            );
    }
}

/// Unauthenticated routes.
///
/// Split from [`api_routes`] because these must sit *outside* the auth,
/// in-flight-tracking and latency-stamping `route_layer`s.
fn public_routes() -> OpenApiRouter<AppState> {
    OpenApiRouter::default()
        .routes(routes!(health::healthz))
        .routes(routes!(health::readyz))
}

/// The authenticated API surface.
///
/// INVARIANT: exactly one `path` value per `routes!(..)` call. `routes!` folds
/// every handler it is given into a single `MethodRouter`, and
/// `OpenApiRouter::routes` then registers that router at *every* distinct path
/// it saw — so mixing paths in one call silently registers a cross-product of
/// methods against paths while documenting only the real operations. There is
/// no compile error for this; `route_table_is_exact` in
/// `crates/siglake-openapi/tests/invariants.rs` is what catches it.
fn api_routes() -> OpenApiRouter<AppState> {
    OpenApiRouter::default()
        .routes(routes!(indexes_routes::create, indexes_routes::list))
        .routes(routes!(
            indexes_routes::get,
            indexes_routes::update,
            indexes_routes::delete
        ))
        .routes(routes!(jaeger_routes::services))
        .routes(routes!(jaeger_routes::operations))
        .routes(routes!(jaeger_routes::find_traces))
        .routes(routes!(jaeger_routes::get_trace))
        .routes(routes!(indexes_routes::list_templates))
        .routes(routes!(
            indexes_routes::put_template,
            indexes_routes::delete_template
        ))
        .routes(routes!(
            delete_tasks_routes::create,
            delete_tasks_routes::list
        ))
        .routes(routes!(delete_tasks_routes::get))
        .routes(routes!(debug_routes::memory_pool))
        .routes(routes!(sql::handle))
        .routes(routes!(sql::explain))
        // Distributed query (#7): `/api/v1/sql` coordinates transparently when
        // peers are configured; `/local` always runs single-pod (the preserved
        // pre-distribution behavior); `/distributed` forces coordination;
        // `/shard` is the worker endpoint.
        .routes(routes!(sql::handle_local))
        .routes(routes!(sql::distributed))
        .routes(routes!(sql::shard))
        .routes(routes!(jobs_routes::status, jobs_routes::cancel))
        .routes(routes!(jobs_routes::result))
}

/// The OpenAPI 3.1 document for the query HTTP API.
///
/// Built from the same route-set constructors [`router`] uses, so a route that
/// exists cannot go undocumented. Takes no [`AppState`]: layers contribute
/// nothing to the document, and `split_for_parts` leaves the state generic.
pub fn openapi() -> utoipa::openapi::OpenApi {
    OpenApiRouter::with_openapi(ApiDoc::openapi())
        .merge(public_routes())
        .merge(api_routes())
        .into_openapi()
}

/// Build the axum router. Public so integration tests can mount it
/// without going through [`serve`].
pub fn router(state: AppState) -> Router {
    let api = api_routes()
        .split_for_parts()
        .0
        .route_layer(middleware::from_fn(track_in_flight))
        .route_layer(middleware::from_fn_with_state(
            state.clone(),
            auth::middleware,
        ))
        // Outermost API layer: stamp total server-side latency on every response
        // so clients (and the bench harness) can separate engine time from
        // network round-trip without a per-handler change. Mirrors the
        // `elapsed_time_micros` convention of inverted-index engines.
        .route_layer(middleware::from_fn(stamp_server_micros))
        // Outermost so auth, extractor and handler responses are all counted
        // from the final status the client receives.
        .route_layer(middleware::from_fn(record_jaeger_request));

    public_routes()
        .split_for_parts()
        .0
        .merge(api)
        // Per-request OTel/tracing server span. Extracts the incoming W3C
        // `traceparent` (so a worker shard span is a child of the coordinator's
        // fan-out span) and records http.method/route/status. With the OTel
        // traces layer installed (`siglake_core::telemetry`) these spans forward
        // as OTel; no-op when OTel is off.
        .layer(middleware::from_fn(otel_http_trace))
        .with_state(state)
}

/// Per-request tracing span that bridges to OpenTelemetry and parents to an
/// incoming W3C `traceparent` when present (distributed query fan-out). The
/// extracted context is attached only for the synchronous span creation (the
/// `ContextGuard` is `!Send` and must not be held across the `next.run().await`),
/// then the span is driven via [`Instrument`] so it propagates across awaits.
async fn otel_http_trace(req: axum::extract::Request, next: Next) -> Response {
    let method = req.method().clone();
    let route = req.uri().path().to_string();
    let parent_cx = global::get_text_map_propagator(|p| p.extract(&HeaderExtractor(req.headers())));
    let span = {
        let _guard = parent_cx.attach();
        tracing::info_span!(
            "http.server",
            otel.kind = "server",
            http.method = %method,
            http.route = %route,
            http.status_code = tracing::field::Empty,
        )
    };
    let span_for_status = span.clone();
    async move {
        let response = next.run(req).await;
        span_for_status.record("http.status_code", response.status().as_u16());
        response
    }
    .instrument(span)
    .await
}

/// Middleware that maintains the `siglake_query_in_flight` gauge for
/// the duration of each API request. Drives the Helm KEDA query scaler and the
/// operator's query autoscaler. Health probes are mounted on a separate router
/// segment and don't move the gauge.
async fn track_in_flight(
    request: axum::extract::Request,
    next: middleware::Next,
) -> axum::response::Response {
    let _guard = QueryInFlightGuard::new();
    next.run(request).await
}

/// Count completed responses from the four Jaeger-compatible read routes.
///
/// The fixed endpoint label keeps the series bounded: index, service, trace id
/// and raw URL never become labels. This sits outside auth and the handlers so
/// every response is counted exactly once, including extractor rejections and
/// handler errors; in particular, `find_traces` still counts once even though
/// it can execute two queries.
async fn record_jaeger_request(
    request: axum::extract::Request,
    next: middleware::Next,
) -> axum::response::Response {
    let is_jaeger_route = request
        .extensions()
        .get::<MatchedPath>()
        .is_some_and(|path| {
            matches!(
                path.as_str(),
                "/api/v1/jaeger/{index}/api/services"
                    | "/api/v1/jaeger/{index}/api/services/{service}/operations"
                    | "/api/v1/jaeger/{index}/api/traces"
                    | "/api/v1/jaeger/{index}/api/traces/{trace_id}"
            )
        });
    let response = next.run(request).await;
    if is_jaeger_route {
        metrics::counter!(
            "siglake_query_requests_total",
            "endpoint" => "jaeger",
            "status" => response.status().as_u16().to_string(),
        )
        .increment(1);
    }
    response
}

/// Holds the `siglake_query_in_flight` gauge for one request, released on Drop.
///
/// The decrement used to sit after `next.run(request).await`, so a request that
/// went away mid-flight -- a client disconnect, or the server's own 60s query
/// timeout -- skipped it and the gauge never came back down. Measured on a live
/// peer on 2026-08-19: **10 in flight while the node was quiescent**, after 24
/// cancelled queries.
///
/// That is not merely a wrong number. This gauge drives query-tier autoscaling,
/// so a leak reads as permanent saturation: the autoscaler adds replicas for
/// load that does not exist and never scales back down. Timeouts are exactly
/// when a system is under stress, which is exactly when the phantom signal
/// appears.
///
/// The ingest side already does this with `InFlightGuard`, and admission with
/// `AdmissionGuard`; this was the one place left doing it inline.
struct QueryInFlightGuard;

/// The same count the gauge carries, readable in-process. The `metrics` facade
/// is write-only, and the memory-gauge tick needs to know whether the pool's
/// reservations coincide with a request or with nothing at all.
static IN_FLIGHT: std::sync::atomic::AtomicI64 = std::sync::atomic::AtomicI64::new(0);

/// Requests currently inside the authenticated API surface (what
/// `siglake_query_in_flight` reports). Health probes are not counted.
pub fn queries_in_flight() -> i64 {
    IN_FLIGHT.load(std::sync::atomic::Ordering::Relaxed)
}

impl QueryInFlightGuard {
    fn new() -> Self {
        IN_FLIGHT.fetch_add(1, std::sync::atomic::Ordering::Relaxed);
        metrics::gauge!("siglake_query_in_flight").increment(1.0);
        Self
    }
}

impl Drop for QueryInFlightGuard {
    fn drop(&mut self) {
        IN_FLIGHT.fetch_sub(1, std::sync::atomic::Ordering::Relaxed);
        metrics::gauge!("siglake_query_in_flight").decrement(1.0);
    }
}

/// Response header carrying total server-side request latency in microseconds.
/// Read by the bench harness as siglake's `server_micros` (the analogue of
/// an `elapsed_time_micros` response field), so client wall time can be decomposed
/// into engine time vs network.
pub const SERVER_MICROS_HEADER: &str = "x-siglake-server-micros";

/// Middleware that stamps [`SERVER_MICROS_HEADER`] with the elapsed time from
/// request entry to response, covering every endpoint and return path (fast
/// path, cached, error) uniformly.
async fn stamp_server_micros(
    request: axum::extract::Request,
    next: middleware::Next,
) -> axum::response::Response {
    let started = std::time::Instant::now();
    let mut resp = next.run(request).await;
    let micros = started.elapsed().as_micros();
    if let Ok(value) = axum::http::HeaderValue::from_str(&micros.to_string()) {
        resp.headers_mut().insert(SERVER_MICROS_HEADER, value);
    }
    resp
}

/// TLS material for [`serve_tls`]: paths to a PEM cert chain + PEM
/// private key. Loaded once at startup; the binary does not reload
/// on SIGHUP (Phase 4.9+).
#[derive(Debug, Clone)]
pub struct TlsConfig {
    pub cert_path: std::path::PathBuf,
    pub key_path: std::path::PathBuf,
}

/// Cadence of the WS-6 hot-cache WAL tail. Freshness of last-value/distinct is
/// bounded by this plus the WAL seal threshold.
pub const HOT_CACHE_REFRESH_INTERVAL: std::time::Duration = std::time::Duration::from_secs(1);

/// Spawn the WS-6 hot-cache background refresher when [`AppState::hot_caches`] is
/// set: every [`HOT_CACHE_REFRESH_INTERVAL`] it folds freshly-sealed WAL
/// segments into each tenant's cache (on a blocking thread, since the scan is
/// synchronous file IO). No-op when hot caches are disabled.
pub fn spawn_hot_cache_refresher(state: &AppState) {
    let Some(registry) = state.hot_caches.clone() else {
        return;
    };
    tokio::spawn(async move {
        let mut tick = tokio::time::interval(HOT_CACHE_REFRESH_INTERVAL);
        tick.set_missed_tick_behavior(tokio::time::MissedTickBehavior::Skip);
        loop {
            tick.tick().await;
            let registry = registry.clone();
            let folded = tokio::task::spawn_blocking(move || registry.refresh_once())
                .await
                .unwrap_or(0);
            if folded > 0 {
                tracing::debug!(segments = folded, "hot-cache refresh folded fresh segments");
            }
        }
    });
}

/// One warm cycle over the events table + every managed index: touch each
/// table's cache entry and warm the query-side caches (live-file list,
/// footers, side-aggregates). On an unchanged table this is all in-memory
/// hits; on a TTL-expired entry it keeps the stale-while-revalidate refresh
/// cycle spinning WITHOUT a query having to arrive — the existing post-refresh
/// hook then warms any new snapshot's files. Returns the number of tables
/// warmed (best-effort per table).
pub async fn warm_all_query_caches(ice: &IcebergContext) -> usize {
    let mut tables = vec!["events".to_string()];
    match ice.list_indexes().await {
        Ok(configs) => {
            tables.extend(
                configs
                    .into_iter()
                    .map(|c| c.index_id)
                    .filter(|id| id != "events"),
            );
        }
        Err(err) => {
            tracing::debug!(error = ?err, "cache warm: list_indexes failed; warming events only");
        }
    }
    let mut warmed = 0usize;
    // Every table in this loop warms into the SAME footer cache, so each gets a
    // share of it rather than budgeting against the whole thing. Without this
    // the per-table bound over-commits the cache N-fold and the thrash it was
    // added to prevent returns with the second table — which is every real
    // deployment: `events` plus at least one index.
    let tables_sharing = tables.len().max(1);
    for table in tables {
        match ice.warm_query_caches_sharing(&table, tables_sharing).await {
            Ok(_) => warmed += 1,
            Err(err) => {
                tracing::debug!(error = ?err, table, "cache warm failed (will warm lazily)");
            }
        }
        // #88: the metadata warm above doesn't touch the ordered-browse path —
        // the newest/oldest-edge parquet footers + first pages an ordered
        // drain reads (match_all cold was 6.8s on the 07-11 board right after
        // a restart). A LIMIT-1 probe in each direction early-stops after
        // exactly those reads, so a warm table costs ~ms per cycle.
        // Best-effort; `SIGLAKE_QUERY_WARM_ORDERED=0` disables.
        if std::env::var("SIGLAKE_QUERY_WARM_ORDERED").as_deref() != Ok("0") {
            if let Err(err) = warm_ordered_edges(ice, &table).await {
                tracing::debug!(error = ?err, table, "ordered-edge warm failed");
            }
        }
        // Merged group-count aggregates: the warmer pays each new snapshot's
        // once-per-snapshot footer merge (multi-second on high-cardinality
        // columns) in the background so user queries only ever see the
        // cached ~ms path. In-memory hits on unchanged snapshots.
        // `SIGLAKE_QUERY_WARM_GROUP_COUNTS=0` disables. Also skipped when result
        // caches are off: the warmer exists to populate the cache nobody would
        // then read, and a background footer merge every cycle is measurement
        // noise in exactly the runs that turn result caches off.
        if std::env::var("SIGLAKE_QUERY_WARM_GROUP_COUNTS").as_deref() != Ok("0")
            && siglake_storage::iceberg::result_caches_enabled()
        {
            if let Err(err) = ice.warm_group_counts(&table).await {
                tracing::debug!(error = ?err, table, "group-count warm failed");
            }
        }
    }
    warmed
}

/// Run `ORDER BY timestamp DESC/ASC LIMIT 1` over `table`'s provider — the
/// cheapest queries that walk the ordered-scan gate and read the leading- and
/// trailing-edge files' footers + first pages (early-stopped).
/// How long one ordered-edge probe may run before it is abandoned.
///
/// THE DEFECT THIS CLOSES. These probes had NO timeout at all. The comment
/// below assumes they early-stop in ~ms on a warm table, and on a converged
/// layout they do (0.4s measured at 2B rows). On an UNCONVERGED layout the same
/// shape is the one that takes 60s and is killed by the user-query timeout —
/// except nothing killed this one, because background work never went through
/// that path.
///
/// Measured 2026-08-24 on a 1TB node: the last warm cycle completed at
/// 05:47:03, the next one hung, and the process then logged nothing but probe
/// responses for **5 hours 24 minutes** while burning 140% CPU with zero
/// queries in flight. No error was ever logged — nothing failed, it hung.
///
/// A background task on a fixed cadence must never be able to run longer than
/// its cadence without bound. The warmer is best-effort by construction: an
/// abandoned cycle simply retries on the next tick.
fn warm_probe_timeout() -> std::time::Duration {
    warm_probe_timeout_from(
        std::env::var("SIGLAKE_QUERY_WARM_PROBE_TIMEOUT_SECS")
            .ok()
            .as_deref(),
    )
}

/// Resolve the warm-probe timeout from its raw environment value.
///
/// Pure so the default and invalid-value behavior can be tested without
/// mutating process-global state observed by parallel tests in this binary.
fn warm_probe_timeout_from(configured: Option<&str>) -> std::time::Duration {
    std::time::Duration::from_secs(
        configured
            .and_then(|v| v.parse::<u64>().ok())
            .filter(|n| *n > 0)
            .unwrap_or(30),
    )
}

async fn warm_ordered_edges(ice: &IcebergContext, table: &str) -> anyhow::Result<()> {
    // The probe browses the table's OWN event time, which for a managed index
    // is whatever its mapping declares (#6020). Reading `timestamp` on a
    // `ts`-mapped index probed a column the table may not even have, and hinted
    // a plan-cache entry no browse of that index could hit.
    let Some(event_time) = ice.index_event_time_field(table).await? else {
        return Ok(()); // not a managed index
    };
    for descending in [true, false] {
        // Same session hints a real browse carries: PreferredScanOrder keys
        // the ordered-plan cache (the warm probe PRE-POPULATES the entry the
        // next browse hits) and OrderedScanLimit engages the small-limit
        // single-partition coalesce, so the probe walks the same plan and
        // fetches the same newest tail chunk into the footer/object caches.
        let mut state = siglake_storage::session_context_with(None, None).state();
        state
            .config_mut()
            .set_extension(Arc::new(siglake_storage::PreferredScanOrder::new(
                event_time.as_str(),
                descending,
            )));
        state
            .config_mut()
            .set_extension(Arc::new(siglake_storage::OrderedScanLimit { limit: 1 }));
        // Arm cancellation, exactly as a real request does. A bare
        // `tokio::time::timeout` would drop this future while its scan kept
        // running -- tokio has no structured concurrency, and DataFusion's
        // spawned pumps outlive the consumer. Abandoning the probe without
        // stopping its scan would leave behind the very residual work the
        // timeout exists to prevent.
        let cancel = siglake_storage::QueryCancel::new();
        state.config_mut().set_extension(Arc::new(cancel.clone()));
        let _cancel_guard = siglake_storage::CancelOnDrop(cancel.clone());
        // The probe scans, so it logs the same two scan events a request does
        // and needs the same identity — otherwise a warm cycle's events are
        // indistinguishable from the request whose log lines they land
        // between. Every probe is its own execution.
        let execution_id = siglake_storage::QueryExecutionId::next();
        state.config_mut().set_extension(Arc::new(execution_id));
        let ctx = datafusion::prelude::SessionContext::new_with_state(state);
        if table == "events" {
            ice.register_with_datafusion(&ctx).await?;
        } else {
            match ice.index_provider_with_consumed(table).await? {
                Some((provider, _, _)) => {
                    ctx.register_table(table, provider)?;
                }
                None => return Ok(()), // not a managed index
            }
        }
        let dir = if descending { "DESC" } else { "ASC" };
        let sql = format!(
            "SELECT \"{event_time}\" FROM \"{table}\" ORDER BY \"{event_time}\" {dir} LIMIT 1"
        );
        crate::sql::log_query_execution_start("warm_ordered_edges", execution_id, Some(&sql), None);
        let probe = async { ctx.sql(&sql).await?.collect().await };
        match tokio::time::timeout(warm_probe_timeout(), probe).await {
            Ok(Ok(_)) => {}
            Ok(Err(err)) => return Err(err.into()),
            Err(_elapsed) => {
                // Best-effort by design: give up on this probe, let the cycle
                // finish, and let the next tick try again. Counted and warned
                // rather than swallowed -- a warmer that silently never warms
                // is the failure this whole area keeps producing.
                metrics::counter!("siglake_query_warm_probe_timeouts_total").increment(1);
                tracing::warn!(
                    table,
                    direction = dir,
                    timeout_secs = warm_probe_timeout().as_secs(),
                    "ordered-edge warm probe timed out and was cancelled; the layout is \
                     probably unconverged. The cycle continues; the next tick retries."
                );
                // `_cancel_guard` fires here, ending the scan rather than
                // leaving it running with no consumer.
            }
        }
    }
    Ok(())
}

/// #79: periodic query-cache warmer. The pre-warm machinery was demand-driven
/// (startup + post-refresh on a stale-serving READ), so a node that goes
/// unqueried lets its table entries age past the staleness ceiling and the
/// next query pays the synchronous metadata reload + manifest walk (the 1–2.7s
/// distributed windowed-aggregate colds on the Phase-4 board). This loop keeps
/// every query-server process — coordinator and workers alike — continuously
/// warm. `SIGLAKE_QUERY_WARM_INTERVAL_SECS` tunes the cadence (default 30s;
/// `0` disables the loop, restoring startup-only warming); the whole feature
/// still honors `SIGLAKE_QUERY_PREWARM=0`.
/// Marks a warm cycle in progress for its whole lifetime, so a cycle that
/// never finishes is distinguishable from one that is not running.
///
/// THE DEFECT THIS CLOSES. `siglake_query_prewarm_total` increments only when a
/// warm completes. A frozen value therefore reads identically to "the warmer is
/// disabled" and to "the warmer is wedged mid-cycle" — opposite conclusions,
/// one benign and one an outage.
///
/// Measured 2026-08-23 on a degraded 1TB node: `prewarm_total` sat at 485 for
/// two hours while the process burned 140% CPU with zero queries in flight. The
/// counter said "not running"; the truth was "stuck since 18:27:43", and only
/// the `query caches warmed` log line distinguished them. That misreading cost
/// a full analysis pass before the log line settled it.
///
/// Same class as the compactor's pass-level counters (see
/// `siglake_compactor_bin_files_removed_total`, 2026-08-15): progress that is
/// only ever recorded on completion cannot report a stall.
///
/// The stuck condition is now directly expressible:
///   `warm_cycle_in_progress == 1` for longer than a few intervals, or
///   `time() - warm_last_completed_seconds > 3 * interval`.
struct WarmCycleProgress {
    completed: bool,
}

impl WarmCycleProgress {
    fn start() -> Self {
        metrics::counter!("siglake_query_warm_cycles_started_total").increment(1);
        metrics::gauge!("siglake_query_warm_cycle_in_progress").set(1.0);
        Self { completed: false }
    }

    fn complete(mut self) {
        metrics::counter!("siglake_query_warm_cycles_completed_total").increment(1);
        metrics::gauge!("siglake_query_warm_last_completed_seconds").set(unix_now_secs());
        self.completed = true;
    }
}

impl Drop for WarmCycleProgress {
    fn drop(&mut self) {
        metrics::gauge!("siglake_query_warm_cycle_in_progress").set(0.0);
        if !self.completed {
            // Cancelled or panicked mid-cycle. Silent before this.
            metrics::counter!("siglake_query_warm_cycles_abandoned_total").increment(1);
        }
    }
}

fn unix_now_secs() -> f64 {
    std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_secs_f64())
        .unwrap_or(0.0)
}

/// Periodically publish memory occupancy: the query pool, and every in-process
/// cache, in BYTES.
///
/// Independent of the warm cycle deliberately. The warmer can stall — it did,
/// for 5h24m on 2026-08-24 — and the moment memory reporting matters most is
/// exactly when other background work has stopped. A gauge that goes quiet
/// alongside the thing it is meant to explain is worth nothing.
///
/// Cheap enough to run often: the pool is two atomic loads and every cache
/// total is maintained incrementally, so nothing here walks cached data.
/// Default query admission budget: the query memory pool's size.
///
/// Was a hardcoded 4 GiB, ignoring the container entirely — the third instance
/// of a defect already fixed twice (`derive_read_cache_bytes` after 24 GiB of
/// caches were found on a 30.8 GiB node, and `derive_bin_concurrency`). On the
/// packaged 4Gi query pod the pool derives to about 1 GiB while admission
/// handed out 4, so admission granted permission the engine could not honour
/// and queries were admitted only to spill or fail; on a 64Gi node the inverse,
/// with admission serialising against 4 GiB while the pool held 19.
///
/// The pool is the right anchor because it is what actually bounds memory.
/// Admission prices ESTIMATED SCAN BYTES, a different and much rougher quantity
/// — so this is not an accounting identity, it is the statement that the two
/// should scale together instead of one being a constant.
///
/// Falls back to the old 4 GiB when the pool is unbounded, so a deployment with
/// no readable limit behaves as it did rather than inheriting a guess.
fn default_admission_budget_bytes() -> u64 {
    match siglake_storage::query_memory_pool_usage() {
        Some((_, limit)) => limit,
        None => 4 * 1024 * 1024 * 1024,
    }
}

pub fn spawn_memory_gauges(ice: Arc<IcebergContext>) {
    let secs = std::env::var("SIGLAKE_MEMORY_GAUGE_INTERVAL_SECS")
        .ok()
        .and_then(|v| v.parse::<u64>().ok())
        .unwrap_or(15);
    if secs == 0 {
        return;
    }
    tokio::spawn(async move {
        let mut tick = tokio::time::interval(std::time::Duration::from_secs(secs));
        tick.set_missed_tick_behavior(tokio::time::MissedTickBehavior::Skip);
        let mut idle_residual = IdleResidualWatch::default();
        loop {
            tick.tick().await;
            siglake_storage::sample_query_memory_pool_gauges();
            ice.sample_cache_gauges().await;
            idle_residual.observe(
                siglake_storage::query_memory_pool_usage().map(|(reserved, _)| reserved),
                queries_in_flight(),
                secs,
            );
        }
    });
}

/// Names the holders of pool bytes that persist while NO request is in flight.
///
/// WHY. `siglake_query_memory_pool_reserved_bytes` read 3.66 GiB after the
/// 2026-09-01 suite with admission at 0, and the scrape could not say whether
/// that was a live query the sampler happened to catch or a reservation that
/// would never return. The two need opposite responses, so the process itself
/// makes the distinction: a reservation that is still there after
/// `IDLE_RESIDUAL_AFTER` of continuous idleness is reported once, with the
/// consumer names the pool tracks, and reported again only if it grows. A live
/// query does not stay idle for a minute; a leak does.
///
/// Background work (the cache warmer's ordered-edge probes, Tier-2 rebuilds)
/// runs outside the in-flight gauge and legitimately holds pool bytes, so this
/// is a warning with names attached, not proof of a leak. The names are what
/// tell the two apart.
#[derive(Default)]
struct IdleResidualWatch {
    idle_secs: u64,
    reported_bytes: u64,
}

impl IdleResidualWatch {
    const IDLE_RESIDUAL_AFTER_SECS: u64 = 60;

    fn observe(&mut self, reserved: Option<u64>, in_flight: i64, tick_secs: u64) {
        let Some(reserved) = reserved else { return };
        if reserved == 0 || in_flight > 0 {
            // Either healthy, or a request is running and the bytes are its
            // working set. Start the idle clock over; the reported mark clears
            // so a reservation that returns and later recurs is reported again.
            self.idle_secs = 0;
            if reserved == 0 {
                self.reported_bytes = 0;
            }
            return;
        }
        self.idle_secs = self.idle_secs.saturating_add(tick_secs);
        if self.idle_secs < Self::IDLE_RESIDUAL_AFTER_SECS || reserved <= self.reported_bytes {
            return;
        }
        self.reported_bytes = reserved;
        let consumers = siglake_storage::query_memory_pool_top_consumers(10)
            .unwrap_or_else(|| "(consumer tracking disabled)".to_string());
        metrics::counter!("siglake_query_memory_pool_idle_residual_reports_total").increment(1);
        tracing::warn!(
            reserved_bytes = reserved,
            idle_secs = self.idle_secs,
            consumers = %consumers,
            "query memory pool holds reservations with no request in flight; \
             these are the consumers that hold them"
        );
    }
}

pub fn spawn_query_cache_warmer(ice: Arc<IcebergContext>) {
    if !siglake_storage::iceberg::query_prewarm_enabled() {
        return;
    }
    let secs = std::env::var("SIGLAKE_QUERY_WARM_INTERVAL_SECS")
        .ok()
        .and_then(|v| v.parse::<u64>().ok())
        .unwrap_or(30);
    if secs == 0 {
        return;
    }
    tokio::spawn(async move {
        let mut tick = tokio::time::interval(std::time::Duration::from_secs(secs));
        tick.set_missed_tick_behavior(tokio::time::MissedTickBehavior::Skip);
        // The first tick fires immediately and doubles as the startup warm.
        // Belt and braces: the per-probe timeout bounds the ordered-edge probes,
        // but the footer walk in `warm_query_caches` is also unbounded I/O. The
        // loop must ALWAYS reach its next tick — on 2026-08-24 it did not for
        // 5h24m — so the whole cycle is bounded too.
        let cycle_cap = std::cmp::max(
            std::time::Duration::from_secs(secs.saturating_mul(4)),
            std::time::Duration::from_secs(120),
        );
        loop {
            tick.tick().await;
            let progress = WarmCycleProgress::start();
            match tokio::time::timeout(cycle_cap, warm_all_query_caches(&ice)).await {
                Ok(warmed) => {
                    progress.complete();
                    tracing::debug!(tables = warmed, "periodic query-cache warm cycle");
                }
                Err(_elapsed) => {
                    // `progress` drops uncompleted here, which counts the
                    // abandonment and clears the in-progress gauge.
                    metrics::counter!("siglake_query_warm_cycle_timeouts_total").increment(1);
                    tracing::warn!(
                        cap_secs = cycle_cap.as_secs(),
                        "query-cache warm cycle exceeded its cap and was abandoned; \
                         the next tick starts a fresh one"
                    );
                }
            }
        }
    });
}

/// Bind to `addr` and serve HTTP until the listener errors.
pub async fn serve(addr: SocketAddr, state: AppState) -> Result<()> {
    spawn_hot_cache_refresher(&state);
    let jobs = state.jobs.clone();
    let listener = tokio::net::TcpListener::bind(addr)
        .await
        .with_context(|| format!("bind {addr}"))?;
    let bound = listener.local_addr()?;
    tracing::info!(
        addr = %bound,
        auth = state.auth.label(),
        max_rows = state.limits.max_rows,
        tls = false,
        "siglake-query-server listening"
    );
    let serve_result = axum::serve(listener, router(state))
        .with_graceful_shutdown(shutdown_signal())
        .await;
    tracing::info!("siglake-query-server stopped accepting connections");
    shutdown_jobs(&jobs).await;
    serve_result.context("axum::serve")
}

/// Retire local batch work only after the HTTP server has drained. Releasing
/// ownership earlier would let a peer condemn a job whose handler was still
/// in the act of submitting or completing it. A failed release is logged but
/// does not turn graceful process termination into a crash: owner upkeep has
/// already stopped, so lease expiry remains the bounded recovery fallback.
async fn shutdown_jobs(jobs: &JobStore) {
    if let Err(e) = jobs.shutdown().await {
        tracing::warn!(
            owner = jobs.owner_id(),
            error = %e,
            "batch-job owner release failed; peers will recover after lease expiry"
        );
    }
}

/// Future that resolves on the first of SIGINT (ctrl-c) or SIGTERM (the
/// kube-default termination signal). Composed into
/// `axum::serve().with_graceful_shutdown(...)` so an in-flight query drains
/// before the stateless query pod exits on scale-down.
async fn shutdown_signal() {
    use tokio::signal::unix::{signal, SignalKind};
    let ctrl_c = async {
        if let Ok(()) = tokio::signal::ctrl_c().await {
            tracing::info!(signal = "SIGINT", "shutdown signal received");
        }
    };
    let sigterm = async {
        match signal(SignalKind::terminate()) {
            Ok(mut s) => {
                s.recv().await;
                tracing::info!(signal = "SIGTERM", "shutdown signal received");
            }
            Err(e) => {
                tracing::warn!(error = %e, "SIGTERM handler unavailable");
                std::future::pending::<()>().await;
            }
        }
    };
    tokio::select! {
        _ = ctrl_c => {}
        _ = sigterm => {}
    }
}

/// Bind to `addr` and serve HTTPS until the listener errors.
/// Uses rustls via `axum-server`; the customer terminates TLS in the
/// binary when there's no Ingress in front of it. (Customers with an
/// Ingress should keep `serve` + ingress termination.)
pub async fn serve_tls(addr: SocketAddr, state: AppState, tls: TlsConfig) -> Result<()> {
    spawn_hot_cache_refresher(&state);
    let jobs = state.jobs.clone();
    // axum-server's `from_pem_file` uses rustls which requires a
    // crypto provider installed in the process. Install aws-lc-rs
    // (the one we already pull in transitively via sqlx) if no
    // default is set yet. Idempotent across multiple TLS servers in
    // the same process.
    let _ = rustls::crypto::aws_lc_rs::default_provider().install_default();

    let rustls_config = axum_server::tls_rustls::RustlsConfig::from_pem_file(
        tls.cert_path.clone(),
        tls.key_path.clone(),
    )
    .await
    .with_context(|| {
        format!(
            "load TLS cert={} key={}",
            tls.cert_path.display(),
            tls.key_path.display()
        )
    })?;
    tracing::info!(
        %addr,
        auth = state.auth.label(),
        cert = %tls.cert_path.display(),
        tls = true,
        "siglake-query-server listening (TLS)"
    );
    let handle = axum_server::Handle::new();
    let shutdown_handle = handle.clone();
    let signal_task = tokio::spawn(async move {
        shutdown_signal().await;
        shutdown_handle.graceful_shutdown(None);
    });
    let serve_result = axum_server::bind_rustls(addr, rustls_config)
        .handle(handle)
        .serve(router(state).into_make_service())
        .await;
    signal_task.abort();
    shutdown_jobs(&jobs).await;
    serve_result.context("axum_server::serve")
}

#[cfg(test)]
mod in_flight_guard_tests {
    use super::*;
    use metrics_util::debugging::{DebugValue, DebuggingRecorder};
    use std::future::Future;

    fn gauge_value(snap: metrics_util::debugging::Snapshot, name: &str) -> Option<f64> {
        snap.into_vec().into_iter().find_map(|(k, _, _, v)| {
            (k.key().name() == name)
                .then(|| match v {
                    DebugValue::Gauge(g) => Some(g.into_inner()),
                    _ => None,
                })
                .flatten()
        })
    }

    /// Poll a guard-holding future once and snapshot: the gauge must be HELD.
    /// Without this, a guard that did nothing at all would pass the release test.
    #[test]
    fn the_gauge_is_held_while_a_request_runs() {
        let recorder = DebuggingRecorder::new();
        let snapshotter = recorder.snapshotter();
        metrics::with_local_recorder(&recorder, || {
            let mut boxed = Box::pin(async {
                let _g = QueryInFlightGuard::new();
                std::future::pending::<()>().await;
            });
            let waker = futures::task::noop_waker();
            let mut cx = std::task::Context::from_waker(&waker);
            assert!(std::pin::Pin::new(&mut boxed).poll(&mut cx).is_pending());
            assert_eq!(
                gauge_value(snapshotter.snapshot(), "siglake_query_in_flight"),
                Some(1.0),
                "gauge must be held while the request is in flight"
            );
            std::mem::forget(boxed); // do not let Drop run before the assert above is scored
        });
    }

    /// The cancellation path -- the one the old inline decrement missed. A
    /// request that goes away mid-flight (client disconnect, or the server's own
    /// 60s timeout) must still put the gauge back. Measured on a live peer
    /// before this fix: 10 in flight while the node was quiescent.
    ///
    /// ONE snapshot only: the debugging recorder drains on each snapshot, so
    /// sampling mid-flight makes the final read a delta (-1) rather than the
    /// net (0), which is how the first version of this test "failed".
    #[test]
    fn a_cancelled_request_releases_the_gauge() {
        let recorder = DebuggingRecorder::new();
        let snapshotter = recorder.snapshotter();
        metrics::with_local_recorder(&recorder, || {
            let mut boxed = Box::pin(async {
                let _g = QueryInFlightGuard::new();
                std::future::pending::<()>().await;
            });
            let waker = futures::task::noop_waker();
            let mut cx = std::task::Context::from_waker(&waker);
            assert!(
                std::pin::Pin::new(&mut boxed).poll(&mut cx).is_pending(),
                "the body must still be running, or this proves nothing"
            );
            drop(boxed); // <- the cancellation
            assert_eq!(
                gauge_value(snapshotter.snapshot(), "siglake_query_in_flight"),
                Some(0.0),
                "a CANCELLED request must release the gauge; leaking it reads as \
                 permanent saturation to the HPA that consumes it"
            );
        });
    }

    /// And the ordinary path still balances.
    #[test]
    fn a_completed_request_releases_the_gauge() {
        let recorder = DebuggingRecorder::new();
        let snapshotter = recorder.snapshotter();
        metrics::with_local_recorder(&recorder, || {
            {
                let _g = QueryInFlightGuard::new();
            }
            assert_eq!(
                gauge_value(snapshotter.snapshot(), "siglake_query_in_flight"),
                Some(0.0)
            );
        });
    }
}

#[cfg(test)]
mod warm_cycle_progress_tests {
    use super::*;
    use metrics_util::debugging::{DebugValue, DebuggingRecorder};

    type Snap = Vec<(
        metrics_util::CompositeKey,
        Option<metrics::Unit>,
        Option<metrics::SharedString>,
        DebugValue,
    )>;

    // ONE snapshot per test: the debugging recorder DRAINS on each snapshot, so
    // a second call reads a delta rather than the state. (That is what made the
    // first version of these tests fail, and it is the same trap already
    // recorded in `in_flight_guard_tests`.)
    fn counter(snap: &Snap, name: &str) -> u64 {
        snap.iter()
            .filter(|(k, _, _, _)| k.key().name() == name)
            .map(|(_, _, _, v)| match v {
                DebugValue::Counter(c) => *c,
                _ => 0,
            })
            .sum()
    }

    fn gauge(snap: &Snap, name: &str) -> Option<f64> {
        snap.iter().find_map(|(k, _, _, v)| {
            (k.key().name() == name)
                .then(|| match v {
                    DebugValue::Gauge(g) => Some(g.into_inner()),
                    _ => None,
                })
                .flatten()
        })
    }

    /// THE PROPERTY THAT WAS MISSING. While a cycle is stuck, the completion
    /// counter cannot move -- so the ONLY thing that can report the stall is
    /// state observable DURING it. This is the exact situation measured on
    /// 2026-08-23: completions frozen for two hours, with no metric saying why.
    #[test]
    fn a_stuck_cycle_is_visible_while_it_is_still_stuck() {
        let recorder = DebuggingRecorder::new();
        let snapshotter = recorder.snapshotter();
        metrics::with_local_recorder(&recorder, || {
            let stuck = WarmCycleProgress::start(); // never completes
            let snap = snapshotter.snapshot().into_vec();

            assert_eq!(counter(&snap, "siglake_query_warm_cycles_started_total"), 1);
            assert_eq!(
                counter(&snap, "siglake_query_warm_cycles_completed_total"),
                0,
                "a cycle that has not finished must not report a completion"
            );
            assert_eq!(
                gauge(&snap, "siglake_query_warm_cycle_in_progress"),
                Some(1.0),
                "a stuck cycle is indistinguishable from a disabled warmer unless \
                 something is observable while it is stuck -- this gauge is that thing"
            );
            std::mem::forget(stuck); // do not let Drop run before the assert is scored
        });
    }

    #[test]
    fn a_completed_cycle_records_completion_and_clears_in_progress() {
        let recorder = DebuggingRecorder::new();
        let snapshotter = recorder.snapshotter();
        metrics::with_local_recorder(&recorder, || {
            WarmCycleProgress::start().complete();
            let snap = snapshotter.snapshot().into_vec();

            assert_eq!(
                counter(&snap, "siglake_query_warm_cycles_completed_total"),
                1
            );
            assert_eq!(
                gauge(&snap, "siglake_query_warm_cycle_in_progress"),
                Some(0.0)
            );
            assert!(
                gauge(&snap, "siglake_query_warm_last_completed_seconds").unwrap_or(0.0)
                    > 1_700_000_000.0,
                "last-completed must be a real unix timestamp so staleness is computable"
            );
            assert_eq!(
                counter(&snap, "siglake_query_warm_cycles_abandoned_total"),
                0
            );
        });
    }

    /// A cycle dropped without completing (cancelled, or panicked) must be
    /// counted as abandoned rather than silently vanishing.
    #[test]
    fn an_abandoned_cycle_is_counted_and_releases_the_gauge() {
        let recorder = DebuggingRecorder::new();
        let snapshotter = recorder.snapshotter();
        metrics::with_local_recorder(&recorder, || {
            drop(WarmCycleProgress::start());
            let snap = snapshotter.snapshot().into_vec();

            assert_eq!(
                counter(&snap, "siglake_query_warm_cycles_abandoned_total"),
                1
            );
            assert_eq!(
                counter(&snap, "siglake_query_warm_cycles_completed_total"),
                0
            );
            assert_eq!(
                gauge(&snap, "siglake_query_warm_cycle_in_progress"),
                Some(0.0),
                "the in-progress gauge must not leak when a cycle dies"
            );
        });
    }
}

#[cfg(test)]
mod warm_probe_timeout_tests {
    use super::warm_probe_timeout_from;

    /// The probes had NO bound at all, which is how one of them hung a process
    /// for 5h24m. The default must be finite and small relative to the cadence:
    /// abandoning a warm probe costs nothing (the next tick retries), while not
    /// abandoning one costs the node.
    #[test]
    fn the_default_is_finite_and_smaller_than_a_stall() {
        let d = warm_probe_timeout_from(None);
        assert!(d.as_secs() > 0, "an unbounded probe is the defect itself");
        assert!(
            d.as_secs() <= 60,
            "a warm probe may not outlive a user query's own 60s ceiling — it is \
             best-effort background work, not a request"
        );
    }

    #[test]
    fn it_is_operator_tunable_and_rejects_zero() {
        assert_eq!(warm_probe_timeout_from(Some("5")).as_secs(), 5);
        // 0 would mean "no timeout" to a careless reader; it must fall back to
        // the default rather than disable the bound.
        assert_eq!(warm_probe_timeout_from(Some("0")).as_secs(), 30);
        assert_eq!(warm_probe_timeout_from(Some("invalid")).as_secs(), 30);
    }
}

#[cfg(test)]
mod otel_disabled_cost_tests {
    use std::time::Instant;

    use axum::body::Body;
    use axum::http::{Request, StatusCode};
    use axum::routing::get;
    use axum::Router;
    use tower::util::ServiceExt;

    use super::otel_http_trace;

    /// What the OTel-off path costs per request, measured rather than asserted.
    ///
    /// The claim on PR #7 was that telemetry costs nothing when it is off. It
    /// does not cost nothing: `otel_http_trace` runs on every request whatever
    /// the configuration — it clones the method, allocates the path `String`,
    /// asks the global propagator to extract (a no-op propagator when
    /// `telemetry::init` installed none), and creates a `tracing` span that no
    /// subscriber is listening to. This measures that residue against the same
    /// handler without the layer, arms interleaved because a single pass on a
    /// loaded box varies several-fold between minutes.
    ///
    /// `#[ignore]`d: it is a measurement, not a bound. A wall-clock ratio
    /// asserted in CI measures the scheduler.
    ///
    /// Run with — `--release`, because the recorded numbers are a release
    /// build's. The default test profile puts all three arms an order of
    /// magnitude higher (bare ~6.7 us/req against ~0.48 us) and reports the
    /// residue as +6.6 us/+2.6 us, which is the profile, not the layer:
    ///   cargo test --release -p siglake-query-server --lib \
    ///     otel_disabled_path_cost -- --ignored --nocapture
    #[tokio::test]
    #[ignore = "measurement, not a bound"]
    async fn otel_disabled_path_cost() {
        const REQUESTS: usize = 2_000;
        const PAIRS: usize = 5;

        let bare = Router::new().route("/healthz", get(|| async { StatusCode::OK }));
        // What this router carried before PR #7: tower-http's per-request span.
        let previous = Router::new()
            .route("/healthz", get(|| async { StatusCode::OK }))
            .layer(tower_http::trace::TraceLayer::new_for_http());
        let layered = Router::new()
            .route("/healthz", get(|| async { StatusCode::OK }))
            .layer(axum::middleware::from_fn(otel_http_trace));

        async fn hammer(app: &Router, n: usize) -> f64 {
            let start = Instant::now();
            for _ in 0..n {
                let req = Request::builder()
                    .uri("/healthz")
                    .body(Body::empty())
                    .expect("request");
                let resp = app.clone().oneshot(req).await.expect("response");
                assert_eq!(resp.status(), StatusCode::OK);
            }
            start.elapsed().as_secs_f64() * 1e9 / n as f64
        }

        // Warm every arm; the first pass pays for lazy initialization.
        hammer(&bare, REQUESTS).await;
        hammer(&previous, REQUESTS).await;
        hammer(&layered, REQUESTS).await;

        let mut vs_bare = Vec::new();
        let mut vs_previous = Vec::new();
        for pair in 0..PAIRS {
            let bare_ns = hammer(&bare, REQUESTS).await;
            let previous_ns = hammer(&previous, REQUESTS).await;
            let layered_ns = hammer(&layered, REQUESTS).await;
            println!(
                "pair {pair}: bare {bare_ns:.0}, TraceLayer {previous_ns:.0}, \
                 otel_http_trace {layered_ns:.0} ns/req"
            );
            vs_bare.push(layered_ns - bare_ns);
            vs_previous.push(layered_ns - previous_ns);
        }
        vs_bare.sort_by(f64::total_cmp);
        vs_previous.sort_by(f64::total_cmp);
        println!(
            "otel-off cost over {PAIRS} pairs of {REQUESTS} requests: \
             median {:+.0} ns/req vs no layer, {:+.0} ns/req vs the TraceLayer \
             this replaced",
            vs_bare[PAIRS / 2],
            vs_previous[PAIRS / 2]
        );
    }
}
