{{- if .Values.externalSecrets.enabled -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.postgres.existingSecret }}
  labels:
    {{- include "siglake.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval | quote }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStore.name }}
    kind: {{ .Values.externalSecrets.secretStore.kind }}
  target:
    name: {{ .Values.postgres.existingSecret }}
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: {{ .Values.externalSecrets.postgres.remoteKey | quote }}
{{- end }}
