{{- $authSecret := include "siglake.ingestTokensSecret" . -}}
{{- if and .Values.ingester.enabled $authSecret (not .Values.ingester.auth.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $authSecret }}
  labels:
    {{- include "siglake.componentLabels" (list . "ingester") | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.ingester.auth.secretKey }}: {{ join "," .Values.ingester.auth.list | quote }}
{{- end }}
