{{- if and .Values.query.enabled (not .Values.query.tokens.existingSecret) -}}
{{- if .Values.query.tokens.list -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "siglake.componentName" (list . "query-tokens") }}
  labels:
    {{- include "siglake.componentLabels" (list . "query") | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.query.tokens.secretKey }}: {{ join "," .Values.query.tokens.list | quote }}
{{- end }}
{{- end }}
