{{- if and .Values.query.enabled (not .Values.query.distributed.coordinatorToken.existingSecret) -}}
{{- if .Values.query.distributed.coordinatorToken.value -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "siglake.componentName" (list . "query-coordinator-token") }}
  labels:
    {{- include "siglake.componentLabels" (list . "query") | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.query.distributed.coordinatorToken.secretKey }}: {{ .Values.query.distributed.coordinatorToken.value | quote }}
{{- end }}
{{- end }}
