{{- if and .Values.ingester.enabled (not .Values.ingester.auth.existingSecret) -}}
{{- if .Values.ingester.auth.list -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "siglake.componentName" (list . "auth-tokens") }}
  labels:
    {{- include "siglake.componentLabels" (list . "ingester") | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.ingester.auth.secretKey }}: {{ join "," .Values.ingester.auth.list | quote }}
{{- end }}
{{- end }}
